image: alpine:latest

stages:
  - test

test:
  stage: test
  before_script:
    - apk add meson vala pc:glib-2.0 pc:gobject-2.0 pc:libsoup-2.4 pc:json-glib-1.0 pc:gee-0.8 pc:libuhttpmock-0.0 openssl alpine-sdk
  script:
    - meson build && meson compile -C build && meson test -v -C build
  tags:
    - ci-build
    - x86_64

coverage:
  image: debian:bullseye-slim
  stage: test
  artifacts:
    paths:
      - coverage
  before_script:
    - apt update
    - env DEBIAN_FRONTEND=noninteractive apt install -fy valac libsoup2.4-dev libglib2.0-dev libjson-glib-dev openssl meson build-essential gcovr curl libgirepository1.0-dev lcov libgee-0.8-dev
    - curl -L -O https://tecnocode.co.uk/downloads/uhttpmock/uhttpmock-0.5.2.tar.xz && tar xf uhttpmock-0.5.2.tar.xz && cd uhttpmock-0.5.2
    - curl -L https://gitlab.alpinelinux.org/alpine/aports/-/raw//13129b99661d439847296d2609e361ccda81e0b4/community/uhttpmock/only-listen-on-ipv4.patch | patch -p1
    - ./configure --enable-vala --enable-introspection && make && make install
    - cd ..
  script:
    - meson _build -Db_coverage=true
    - env LD_LIBRARY_PATH=/usr/local/lib meson test -C _build -t 100 --print-errorlogs --verbose
    - cd _build/alpine-qa-bot
    - lcov -d . -o lcov.info -c
    - lcov -d . -o lcov.info -r lcov.info "*/_build/*"
    - genhtml -t "alpine-qa-bot" -o ../../coverage lcov.info
    - lcov -l lcov.info
  coverage: '/Total:\| *(\d+\.?\d+\%)/'
  tags:
    - ci-build
    - x86_64
