image: alpine:latest

stages:
  - test

test:
  stage: test
  before_script:
    - apk add meson vala glib-dev libsoup-dev json-glib-dev uhttpmock-dev alpine-sdk openssl
  script:
    - meson build && ninja -C build test
