image: alpine:latest

stages:
  - test

test:
  stage: test
  before_script:
    - apk add meson vala glib-dev libsoup-dev json-glib-dev uhttpmock-dev alpine-sdk openssl
  script:
    - meson build && ninja -C build test

coverage:
  image: debian:bullseye-slim
  stage: test
  artifacts:
    paths:
      - coverage
  before_script:
    - env DEBIAN_FRONTEND=noninteractive apt install -fy valac libsoup2.4-dev libglib2.0-dev libjson-glib-dev openssl meson build-essential gcovr curl libgirepository1.0-dev lcov
    - curl -L -O https://tecnocode.co.uk/downloads/uhttpmock/uhttpmock-0.5.2.tar.xz && tar xf uhttpmock-0.5.2.tar.xz && cd uhttpmock-0.5.2
    - curl -L https://gitlab.alpinelinux.org/alpine/aports/-/raw//13129b99661d439847296d2609e361ccda81e0b4/community/uhttpmock/only-listen-on-ipv4.patch | patch -p1
    - ./configure --enable-vala --enable-introspection && make && make install
    - cd ..
  script:
    - meson _build -Db_coverage=true
    - meson test -C _build -t 100 --print-errorlogs --verbose
    - cd _build/src
    - lcov -d . -o lcov.info -c
    - lcov -d . -o lcov.info -r lcov.info "*/_build/*"
    - genhtml -t "gpseq" -o ../../coverage lcov.info
    - lcov -l lcov.info
  coverage: '/Total:\| *(\d+\.?\d+\%)/'
